# Generated by Django 5.0.3 on 2024-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_voluntario_cadastro_atividades_que_gostaria_de_executar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao_cadastro',
            old_name='nome_do_Doador',
            new_name='ID_doacao',
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Contato',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Data_Limite_para_Doacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Item_Necessario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Voluntario_Responsavel_pela_Captacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
