# Generated by Django 5.0.3 on 2024-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_voluntario_cadastro_atividades_que_gostaria_de_executar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario_cadastro',
            name='Atividades_que_gostaria_de_executar',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voluntario_cadastro',
            name='Dias_disponiveis_para_atuar',
            field=models.TextField(default=''),
        ),
    ]
