# Generated by Django 5.0.3 on 2024-05-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao_Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_Doador', models.CharField(max_length=100, unique=True)),
                ('Data_da_Doacao', models.DateField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Celular', models.CharField(blank=True, max_length=11, null=True)),
                ('Itens_da_Doacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario_Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_voluntario', models.CharField(max_length=100, unique=True)),
                ('Data_de_nascimento', models.DateField(blank=True, null=True)),
                ('Endereco', models.CharField(max_length=300, unique=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Celular', models.CharField(blank=True, max_length=11, null=True)),
                ('Dias_disponiveis_para_atuar', models.TextField()),
                ('Atividades_que_gostaria_de_executar', models.TextField()),
            ],
        ),
    ]
