# Generated by Django 5.0.3 on 2024-05-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_doacao_cadastro_id_doacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='Atividades_que_gostaria_de_executar',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='Celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='Dias_disponiveis_para_atuar',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='Endereco',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='voluntario_cadastro',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario_cadastro',
            name='nome_do_voluntario',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
