# Generated by Django 5.0.3 on 2024-05-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_nome_do_doador_doacao_cadastro_id_doacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao_cadastro',
            name='ID_doacao',
        ),
        migrations.AddField(
            model_name='doacao_cadastro',
            name='Quantidade_Necessaria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
