# Generated by Django 5.0.3 on 2024-11-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "polls",
            "0007_alter_voluntario_cadastro_atividades_que_gostaria_de_executar_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="atendidos_cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_do_atendido", models.CharField(max_length=300, null=True)),
                ("data_de_nascimento", models.DateField(blank=True, null=True)),
                ("Endereco", models.CharField(max_length=300, null=True)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Celular", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="newsletter_cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_assinante", models.CharField(max_length=300, null=True)),
                ("data_de_nascimento", models.DateField(blank=True, null=True)),
                ("Email", models.EmailField(blank=True, max_length=254, null=True)),
                ("Celular", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
